export const COLORS = {
    PRIMARY_BACKGROUND: "#404040",
    PRIMARY_TEXT: "#fff",
    SECONDARY_BACKGROUND: "#202020",
    SECONDARY_TEXT: "#000",
    TERTIARY_BACKGROUND: "#303030",
    TERTIARY_TEXT: "#fff",
}